server:
  port: 8080
  servlet:
    context-path: /student-manager

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springboot_react_student_manager"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true